### ISSUE TITLE
US01 - Cadastro de Usuários

### ISSUE THREAD

**Issue by EduardoPicolo** [fga-eps-mds/2022-1-schedula-doc#18]
## Descrição
Eu, como usuário, desejo me cadastrar no sistema para eu conseguir usufruir de todas as funcionalidades do sistema

## Critérios de Aceitação (se aplicável)
- [ ] Deve ser possivel inserir um novo usuário no sistema;
- [ ] Deve ser possivel editar um usuário já cadastrado;
- [ ] Deve ser possivel excluir um usuário já cadastrado;
- [ ] Deve ser possivel consultar um usuário cadastrado;

**Comment by Sayuck** [comment]
Cadastrar Usuários:

![image.png](https://images.zenhubusercontent.com/62c0897d1126ca62747cb471/2430fbfb-7964-4440-b542-d8975f725d8e)

Editar Usuário:

![image.png](https://images.zenhubusercontent.com/62c0897d1126ca62747cb471/424b5aff-0cf1-4653-beba-df6891602e4c)

Listar Usuários (admin)

![image.png](https://images.zenhubusercontent.com/62c0897d1126ca62747cb471/5d626557-7876-4a88-82fe-ae5826531f32)
