### ISSUE TITLE
US03 - Cadastro de Chamados

### ISSUE THREAD

**Issue by EduardoPicolo** [fga-eps-mds/2022-1-schedula-doc#19]
## Descrição
Eu, como usuário, desejo cadastrar Chamados para que seja possivel fazer o controle e organizar atendimentos dos mesmos

## Critérios de Aceitação
- [ ] Deve ser possível inserir um novo chamado no sistema;
- [ ] Ao inserir novo chamado deve ser possível finalizar o atendimento ou reaproveitar(Nome solicitante, regional, cidade e telefone solicitante) informações do ultimo chamado em um novo chamado.
- [ ] Cada novo chamado deve ter uma data e hora automáticos.
- [ ] Deve ser possível editar um chamado já registrado;
- [ ] Deve ser possível excluir um chamado já registrado;
- [ ] Deve ser possível listar todos os chamados;
- [ ] Deve ser possível filtrar chamados por data, local, cidade, tipo de chamado e status;

**Comment by SamuelNoB** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workstation-62bddf98961b28001b52d032/issues/fga-eps-mds/2022-1-schedula-doc/19?planning-poker) with ZenHub @Pedrok99 @Sayuck @EduardoPicolo

**Comment by SamuelNoB** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workstation-62bddf98961b28001b52d032/issues/fga-eps-mds/2022-1-schedula-doc/19?planning-poker) with ZenHub @Matheus73
