### ISSUE TITLE
US02 - Autenticação de Usuários

### ISSUE THREAD

**Issue by EduardoPicolo** [fga-eps-mds/2022-1-schedula-doc#20]
## Descrição:
- Eu, como usuário, desejo acessar o sistema com minhas credenciais para que eu consiga utilizar todas as funcionalidades dele.

## Critérios de Aceitação:
- [ ] Deve ser possível realizar a autenticação com usuário e senha;

- [ ] Deve ser possível realizar a autenticação com email e senha.

**Comment by daves22** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workstation-62bddf98961b28001b52d032/issues/fga-eps-mds/2022-1-schedula-doc/20?planning-poker) with ZenHub @Algusto-RC

**Comment by daves22** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workstation-62bddf98961b28001b52d032/issues/fga-eps-mds/2022-1-schedula-doc/20?planning-poker) with ZenHub @RodrigoWright

**Comment by daves22** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workstation-62bddf98961b28001b52d032/issues/fga-eps-mds/2022-1-schedula-doc/20?planning-poker) with ZenHub @nszchagas

**Comment by daves22** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workstation-62bddf98961b28001b52d032/issues/fga-eps-mds/2022-1-schedula-doc/20?planning-poker) with ZenHub @brun0sk

**Comment by daves22** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workstation-62bddf98961b28001b52d032/issues/fga-eps-mds/2022-1-schedula-doc/20?planning-poker) with ZenHub @Alpha-Brutaka

**Comment by daves22** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workstation-62bddf98961b28001b52d032/issues/fga-eps-mds/2022-1-schedula-doc/20?planning-poker) with ZenHub @giovanni1106
