### ISSUE TITLE
US04 - Gerência de Tipo de Problema

### ISSUE THREAD

**Issue by EduardoPicolo** [fga-eps-mds/2022-1-schedula-doc#21]
## Descrição
Eu, como usuário, desejo cadastrar tipos de problema para que ajudem a categorizar os chamados

## Critérios de Aceitação (se aplicável)
- [ ] Deve ser possivel inserir tipos de problema no sistema;
- [ ] Os tipos cadastrados devem ser unicos;
- [ ] Deve ser possível editar um tipo previamente cadastrado;
- [ ] Deve ser possivel excluir um tipo de problema;
- [ ] Deve ser possivel listar os tipos de problemas;

**Comment by Sayuck** [comment]
Listagem Categoria Problema:

![image.png](https://images.zenhubusercontent.com/62c0897d1126ca62747cb471/ed07ba56-51c6-46d4-b240-f8b1df75ae89)

Cadastrar Categoria Problema:

![image.png](https://images.zenhubusercontent.com/62c0897d1126ca62747cb471/cbe9f79e-678d-4976-bd6a-79cd2145004f)

Editar Categoria Problema:

![image.png](https://images.zenhubusercontent.com/62c0897d1126ca62747cb471/91d671a7-b4bd-4d3e-ab87-352cedf6ba64)

Excluir Categoria Problema:

![image.png](https://images.zenhubusercontent.com/62c0897d1126ca62747cb471/1d19dd2f-bee8-4061-996c-ba5d3627ca43)

Listar Tipo Problema:

![image.png](https://images.zenhubusercontent.com/62c0897d1126ca62747cb471/6768c03e-d607-4562-ac31-d7fb76d2eb39)

Cadastrar Tipo Problema:

![image.png](https://images.zenhubusercontent.com/62c0897d1126ca62747cb471/36c43be1-dab1-45b5-b837-1e99e186b7ec)

Editar Tipo Problema:

![image.png](https://images.zenhubusercontent.com/62c0897d1126ca62747cb471/053f72fc-ff78-497d-88f5-f02f08ef19ad)

Excluir Tipo Problema:

![image.png](https://images.zenhubusercontent.com/62c0897d1126ca62747cb471/dda9dba7-69f0-4ccc-8ea3-be6b0b8658c5)
