### ISSUE TITLE
US05 - Gerenciar regionais

### ISSUE THREAD

**Issue by SamuelNoB** [fga-eps-mds/2022-1-schedula-doc#23]
# Descrição
Eu como usuário, quero poder gerenciar as regionais de modo a atrela-las a uma cidade

# Critérios de Aceitação (Se aplicável)

- [ ] Deve ser possível Adicionar uma nova regional ao sistema;
- [ ] Deve ser possível editar uma regional já cadastrada;
- [ ] Deve ser possível excluir uma regional já cadastrada;
- [ ] Deve ser possivel consultar uma regional cadastrada;

**Comment by Matheus73** [comment]
Na reunião com o cliente no dia 26/07 foi definido que a lógica de regionais seria vinculada a US de posto de trabalho
