### ISSUE TITLE
US06 Gerenciar cidades

### ISSUE THREAD

**Issue by SamuelNoB** [fga-eps-mds/2022-1-schedula-doc#24]
Eu como usuário, quero poder gerenciar cidades do estado do goiás

# Critérios de Aceitação (Se aplicável)

- [ ] Deve ser possível Adicionar uma nova cidade ao sistema;
- [ ] Deve ser possível editar uma cidade já cadastrada;
- [ ] Deve ser possível excluir uma cidade já cadastrada;
- [ ] Deve ser possivel consultar uma cidade cadastrada;

**Comment by Matheus73** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workstation-62bddf98961b28001b52d032/issues/fga-eps-mds/2022-1-schedula-doc/24?planning-poker) with ZenHub @brun0sk @EduardoPicolo @Pedrok99 @SamuelNoB @Sayuck @Algusto-RC @nszchagas @RodrigoWright

**Comment by Sayuck** [comment]
Listar Cidades:

![image.png](https://images.zenhubusercontent.com/62c0897d1126ca62747cb471/82bfc12a-2788-4657-8b45-ea41edd43b26)

Cadastrar Cidade:

![image.png](https://images.zenhubusercontent.com/62c0897d1126ca62747cb471/2ff3f211-31c1-47aa-8490-42ebaeafb03c)

Editar Cidade:

![image.png](https://images.zenhubusercontent.com/62c0897d1126ca62747cb471/59020056-4d9b-4b34-9831-859d1b467511)

Excluir Cidade:

![image.png](https://images.zenhubusercontent.com/62c0897d1126ca62747cb471/a0d73828-b3dc-46e5-afd6-789418b5938b)

**Comment by RodrigoWright** [comment]
Listar cidades:
![Captura de tela de 2022-08-19 21-51-23](https://user-images.githubusercontent.com/72146155/185723022-a3ea4509-8e63-45ca-bace-9ab191effbd2.png)
