### ISSUE TITLE
US07 - Gerenciar posto de trabalho

### ISSUE THREAD

**Issue by SamuelNoB** [fga-eps-mds/2022-1-schedula-doc#25]
# Descrição
Eu como usuário, quero poder gerenciar os postos de trabalho

# Critérios de Aceitação (Se aplicável)

- [ ] **Um posto de trabalho pode ser uma regional;**
- [ ] Deve ser possível Adicionar um novo posto de trabalho ao sistema;
- [ ] Deve ser possível editar um  posto de trabalho já cadastrado;
- [ ] Deve ser possível excluir um  posto de trabalho já cadastrado;
- [ ] Deve ser possivel consultar um  posto de trabalho cadastrado;

**Comment by Matheus73** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workstation-62bddf98961b28001b52d032/issues/fga-eps-mds/2022-1-schedula-doc/25?planning-poker) with ZenHub @Pedrok99 @SamuelNoB @EduardoPicolo @Sayuck @brun0sk

**Comment by Matheus73** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workstation-62bddf98961b28001b52d032/issues/fga-eps-mds/2022-1-schedula-doc/25?planning-poker) with ZenHub @nszchagas @RodrigoWright @Algusto-RC

**Comment by Sayuck** [comment]
Listar Posto de Trabalho:

![image.png](https://images.zenhubusercontent.com/62c0897d1126ca62747cb471/fc810cc6-c992-47ab-8db0-db45e6e3f855)

Cadastrar Posto de Trabalho:

![image.png](https://images.zenhubusercontent.com/62c0897d1126ca62747cb471/372e6495-a283-4f00-bb3b-188dd9fe01ac)

![image.png](https://images.zenhubusercontent.com/62c0897d1126ca62747cb471/f5bac7c3-c172-4339-99b4-f728500dfa53)

![image.png](https://images.zenhubusercontent.com/62c0897d1126ca62747cb471/9a21e1bc-ff5a-4943-ba6c-f17440caa427)

Editar Posto de Trabalho:

![image.png](https://images.zenhubusercontent.com/62c0897d1126ca62747cb471/1d7f8adf-0e01-43e2-8362-bfcff3dc7836)

Excluir Posto de Trabalho:

![image.png](https://images.zenhubusercontent.com/62c0897d1126ca62747cb471/31cd2310-7ac6-4c5c-be25-7dc3d393ef28)
